### ISSUE TITLE
Getting duplicate documents when parent changes

### ISSUE THREAD

**Issue by benbenwilde** [couchbase/couchbase-elasticsearch-connector#120]
Two of my mappings in elasticsearch are called `groups`, and `groupTypes`. `groupTypes` are parents of  `groups`. 

I have the parent child relationship configured in the transport settings as follows:

```
couchbase.parentSelector.documentTypeParentFields.group: doc.groupTypeId
couchbase.documentTypeRoutingFields.group: doc.groupTypeId
```

In my application it is totally valid for the parent of a group to change, but when it does, it is duplicated in elasticsearch.

Any ideas on how to handle this scenario correctly?

**Comment by Branor** [comment]
That's not easy to fix, because the plugin doesn't know that the parent has changed, so it can't remove the old relation. It will just add the new one.

**Comment by benbenwilde** [comment]
The plugin has checkpoints and stuff, can we track routing for each document? Always using default routing, yet supporting custom routing and parent child relationships is a problem in itself. Today, you never truly know if a document is added or updated, because you support custom routing. But I'm glad you support custom routing.

We are working around this by manually searching for and deleting all documents with different parents than the current parent in elasticsearch after updating the Couchbase document.

**Comment by dnault** [comment]
Going forward, the connector aims for compatibility with ES 6 which does not support parent/child relationships... so we're probably not going to tackle this issue.
