### ISSUE TITLE
the plugin overwrites newer revision with older revision if request comes out of order

### ISSUE THREAD

**Issue by ahmed-sharif** [couchbase/couchbase-elasticsearch-connector#125]
Here you are checking if elastic search already have the same revision of the document. 

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/blob/master/src/main/java/org/elasticsearch/transport/couchbase/capi/ElasticSearchCAPIBehavior.java#L228

But how about if request comes with an older revision than what Elastic search already have? Currently the newer revision is overwritten by the older version.

I am not sure if anyone else faced this issue, but recently I was hit by this bug. In my current setup I have 3 CB clusters in different geographic location. They have XDCR in place among them. One of the cluster also replicates data to elastic search. Every now and then I see inconsistent replication behavior in elastic search side. To degug the issue I enabled "TRACE" log and found that sometime request comes with older revision than what we already have in elastic-search. Since the plugin does not check which version is newer, it ends up with inconsistent revision of the document in elasticsearch. For example: the request to index revision 9-007f50323ef372b10000000000000000 can come while we already have revision 14-0080d2472a18429f0000000000000000 and revision 14 will be replaced by revision 9.

To give you an idea about how I am using couchbase: the application creates a document and within a few seconds the same document is modified by different parts of the application. Every time the document is written, XDCR propagates the change to elasticsearch.

Looks like it would be trivial to add another check to make sure older revision will be discarded:
    - extract the numeric revision number form the revision string (split at '-' and take the first part)
    - compare with the existing one and discard if older 

Let me know if the problem I describe make sense.

Also are you open to code contribution? If yes, I can send a pull request with the above solution I proposed.

Btw, I am using version 2.1.2 of the plugin and version 1.4 of elastic search.

**Comment by dnault** [comment]
Hi Amed, thanks for identifying this issue and sorry for the belated response. Code contributions are most welcome! If you're still interested, we would ask that you create an account on the [Couchbase Gerrit server](http://review.couchbase.org) and sign the Contributor License Agreement.

**Comment by dnault** [comment]
Recommend upgrading to version 4 of the connector which uses a different protocol to listen for database changes, and should not be affected by this issue.
