### ISSUE TITLE
Date epoch MapperParsingException

### ISSUE THREAD

**Issue by amg84** [couchbase/couchbase-elasticsearch-connector#137]
Using couchbase 4.1.0 replicating to elasticsearch 2.3.4, with elasticsearch-transport-couchbase-2.2.3.4. The data in the document field is: "tagged_on": 1472158799999 and the mapping for the field is: "type": "date", "format": "epoch_millis".
This is the error I get MapperParsingException[failed to parse [doc.tagged_on]]; nested: IllegalArgumentException[Invalid format: "1.472158799999E12"].

I use millisecond epoch for a number of fields and tagged_on is the only field causing this issue.

This is the full mappings used: 
https://gist.github.com/anonymous/9035e0a4ac5680be29d56e4c73ddea69

a document that is failing to index:
https://gist.github.com/anonymous/c3cd0b0326670e424570803bce858349

a document that is not failing to index: 
https://gist.github.com/anonymous/cc7986144af1cb2a8fe29aef7f26c83a

this is me inserting a tagged_on into elasticsearch directly:
https://gist.github.com/anonymous/42aee799350b0091310ddf3b3a40dc2f

**Comment by led42** [comment]
Looks like the same thing as this bug: https://github.com/couchbase/sync_gateway/issues/694

**Comment by dnault** [comment]
Can't reproduce this with Couchbase Server 5.5.0. Not sure when this got resolved, but I suspect it was quite a while ago. Please re-open if I'm mistaken and this is still happening with recent versions of Couchbase.
