### ISSUE TITLE
Cannot find remote cluster

### ISSUE THREAD

**Issue by shabailiu** [couchbase/couchbase-elasticsearch-connector#144]
I'm following [this guide](http://developer.couchbase.com/documentation/server/4.0/connectors/elasticsearch-2.1/index-query.html) to set up replication to ElasticSearch, and it is failing on the Create Replication step. I always get this error:
```
{"errors":{"toCluster":"cannot find remote cluster\n err = Failed to connect to cluster reference remoteCluster/M2agU_JOQAe8cvubLOJFNc-FFKDH2CUqBVbcHqJzzRc=\n"}}
```

These are the commands I used to create the remote cluster:
```
couchbase-cli xdcr-setup -c localhost:8091 --create --xdcr-cluster-name=ES --xdcr-hostname=localhost:9091 --xdcr-username=Administrator --xdcr-password=password -u Administrator -p password
```
which returns `SUCCESS: init/edit ES`
and to create replication:
```
couchbase-cli xdcr-replicate -c localhost:8091 --create --xdcr-cluster-name=ES --xdcr-from-bucket=reports --xdcr-to-bucket=reports -u Administrator -p password
```
which returns the error displayed above.

I'm running Couchbase 4.6.0-3453 and ElasticSearch 2.4.0.

**Comment by shabailiu** [comment]
I just tried with a Couchbase 4.0.0 installation and it worked. I don't think 4.6.0 is supported in this plugin.

**Comment by koresar** [comment]
Faced the same problem today.
> `cannot find remote cluster err = Failed to connect to cluster reference remoteCluster/XXXXXXX`

However, I can't install CB 4.0.0 or 4.5.1 or anything but v4.6.0 because I'm running OS X **Sierra**.

Any help or ideas are very welcome.

**Comment by stakach** [comment]
I have the same problem as @koresar which makes development very difficult

**Comment by koresar** [comment]
Temporary, I fixed by installing the v4.5.1. The ES XDCR transport works.
Except that the `goxdcr` process is starting to use 100% CPU. I just kill it. It helps for a period of time. Then I kill it again. :) Like once an hour.

**Comment by erpankaj22** [comment]
I got the same issue "cannot find remote cluster err = Failed to connect to cluster reference remoteCluster/tSuocSQaJUkgl-BdFw--3a0DfS7PZtm9iED0YlYIjv0"

Is it possible to have a work around by installing a couch base 4.0 cluster and replicate that with main cluster and then link that with elastic search.

**Comment by dnault** [comment]
Recommend upgrading to version 4 of the connector which does not require setting up XDCR.
