### ISSUE TITLE
Custom mapping sample

### ISSUE THREAD

**Issue by israelolcha** [couchbase/couchbase-elasticsearch-connector#146]
Hi,

I tried to look for a simple example of custom mapping and all I found is a bunch of frustrated users who couldn't get an answer.
Is it possible to provide with a simple example with 2 different models and how can I do mapping of specific properties ?
Thanks

**Comment by dnault** [comment]
Type mappings are a [general Elasticsearch concept](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html). There's nothing special about how they're used with the connector. That said, we can probably do better in this area as we assemble the documentation for version 4 of the connector.

In the mean time, here's an article from Cambium Consulting (an unrelated third party):  [Our Favorite Elasticsearch Features: Part 1 - Explicit Mapping](https://cambium.consulting/articles/2018/2/20/mappings-aliases-and-index-templates-three-of-our-favorite-elasticsearch-features) that includes some examples and does a nice job explaining the concepts.

**Comment by dnault** [comment]
Version 4 of the connector no longer stores replication state in Elasticsearch, so custom mappings are no longer required.
