### ISSUE TITLE
Unbalanced load on Elasticsearch cluster nodes

### ISSUE THREAD

**Issue by lucabelluccini** [couchbase/couchbase-elasticsearch-connector#151]
Hello,
We are replicating data from Couchbase to Elasticsearch 2.4.3 using the matching version (elasticsearch-transport-couchbase-2.2.4.3.zip).

The Cluster is composed of 3 master only nodes and 3 data only nodes. All the nodes have the settings and the plugin installed.
There is no special routing, infact data seems evenly distributed across the cluster.

I get this in the _cat/thread_pool

bulk.active bulk.queue bulk.rejected index.active index.queue index.rejected search.active search.queue search.rejected 
3          0             0            0           0              0             0            0               0 
0          0             0            0           0              0             0            0               0 
0          0             0            0           0              0             0            0               0 
0          0             0            0           0              0             0            0               0 
8356             0            0           0              0             0            0               0 
8          0             0            0           0              0             0            0               0

It seems data is being queued on a specific node, even if all the data nodes have the same specs.
Under Transport, I can identify the node which is queueing is also receiving a little more Transport packets and amount of data. It is a slight discrepancy but in any case can be seen easily spotted on our dashboards.

**Comment by dnault** [comment]
Recommend upgrading to version 4 of the connector which is now a separate processes that sends bulk indexing requests to ES nodes over HTTP(S)  in round-robin fashion.
