### ISSUE TITLE
Assigning types based on doc attributes

### ISSUE THREAD

**Issue by tunix** [couchbase/couchbase-elasticsearch-connector#164]
Hi,

I've been using Couchbase for a while and now I'm experimenting with ElasticSearch as part of a new feature. My bucket in Couchbase already has lots of documents in it with ID's in UUID. The documents are written by `spring-couchbase` so they have a `_class` field which I want to map to ES' `_type` attribute.

I think it'd be nice to have such a feature to map documents during replication with something other than document id. What do you think?

**Comment by dnault** [comment]
Agreed, sounds like a nice idea.

**Comment by dnault** [comment]
@tunix [Mapping types are removed in Elasticsearch 6.0.0](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html) and each index will only support a single document type, with the recommendation that different types be stored in separate indexes.

For this enhancement request, would it be appropriate to assign documents to different *indexes* based on a field of the document (or document ID)?

**Comment by tunix** [comment]
I'm totally fine with this. I think it's more important than before to have a customizable field within the document when this change is implemented.

**Comment by dnault** [comment]
Issue migrated to Couchbase Jira: https://issues.couchbase.com/browse/CBES-91

Couchbase Jira is open to everyone. If you don't already have an account, sign up by clicking the "contact your Jira administrators" link on the login form.
