### ISSUE TITLE
XDCR dropping replications

### ISSUE THREAD

**Issue by rajeshetty** [couchbase/couchbase-elasticsearch-connector#165]
We are on 4.6.2-3905 Enterprise Edition (build-3905). We are seeing following error on the admin console log and our xdcr replication is getting removed completely.

Replication from bucket "XXX" to bucket "XXX" on cluster "elasticsearchcluster" removed, since spec d9bc3abd3f6d3d6b8edd4b3e47e93532/XXX/XXX refers to bucket XXX which was deleted and recreated"

XDCR is sending data to elastic search cluster and I do not see any issues on elastic search side and indexes on elastic search side is intact.

**Comment by bgabler** [comment]
We're seeing the same issue as above using Elastic 5.6.3

**Comment by rajeshetty** [comment]
We moved to 4.6.1 enterprise edition and we no longer have that problem. I would imagine that it should have been fixed in 4.6.2 > version onwards .

**Comment by dnault** [comment]
Recommending upgrading to version 4 of the connector, which no longer requires setting up XDCR.
