### ISSUE TITLE
Add setting for conflict resolution type sent to Couchbase when creating replication

### ISSUE THREAD

**Issue by leitzler** [couchbase/couchbase-elasticsearch-connector#166]
When conflict resolution is disabled it should be possible to set what the transport plugin bucket present itself as upon creation of a new replication.

Adding a setting for conflict resolution type would resolve https://issues.couchbase.com/browse/MB-25202.

**Comment by dnault** [comment]
Recommending upgrading to version 4 of the connector, which no longer uses CAPI. Instead it uses the DCP protocol, which does not need to deal with conflict resolution.
