### ISSUE TITLE
Couchbase 4.6.3 and Elasticsearch 5.6.3 Failed to get bucket info

### ISSUE THREAD

**Issue by bgabler** [couchbase/couchbase-elasticsearch-connector#176]
We're trying to setup the XDCR for Elasticsearch 5.6.3 and getting the following error:

```
Attention - 2017-10-31 14:23:48 server4.internal:Failed to get bucket info.
Attention - 2017-10-31 14:23:38 server4.internal:Failed to get bucket info.
```

We've installed the appropriate transport plugin for 5.6.3 and the XDCR to an Elasticsearch 2.x server works perfectly fine using the same settings.

**Comment by bgabler** [comment]
It looks like it's related to an Elasticsearch 5.6.3 work around to listen on 0.0.0.0 or a private IP at google cloud.

```
[2017-10-31T14:33:48,686][INFO ][o.e.t.c.CouchbaseCAPI    ] [elasticsearch-56] publish_address {10.128.0.30:9091}, bound_addresses {0.0.0.0:9091}
[2017-10-31T14:33:48,872][INFO ][o.e.t.TransportService   ] [elasticsearch-56] publish_address {10.128.0.30:9300}, bound_addresses {10.128.0.30:9300}
[2017-10-31T14:33:48,891][INFO ][o.e.b.BootstrapChecks    ] [elasticsearch-56] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
```

The work around for this is https://github.com/elastic/elasticsearch/issues/19987#issuecomment-298597068 but then the connector tries to set localhost as the transport layer for plugins.

**Comment by bgabler** [comment]
I was able to solve this by setting

```
transport.host:  $google-cloud-compute-hostname
http.host: $google-cloud-compute-hostname
```

Might be helpful for other users.

**Comment by dnault** [comment]
Can you elaborate on the steps required to reproduce this issue?

**Comment by dnault** [comment]
Recommending upgrading to version 4 of the connector which runs as a separate process and does not share network configuration with Elasticsearch.
