### ISSUE TITLE
[Connector Service] Dynamically infer the index name from document ID

### ISSUE THREAD

**Issue by shays10** [couchbase/couchbase-elasticsearch-connector#194]
As a followup to this [StackOverflow discussion](https://stackoverflow.com/questions/48041274/replicating-couchbase-to-elasticsearch-w-multiple-indices/52108034?noredirect=1#comment91977948_52108034)
it would be great if we can automatically route documents according to a prefix + delimiter.
For example
account::123 -> account index
user::456 -> user index
and so on.

Currently we are only able to specify behaviours to hardcoded types. (We have to explicitly mention that all documents that starts with airplane_ -> airplanes index ) and the documents that didn't match any of the rules can be routed to only a single index.

**Comment by dnault** [comment]
Sample type definition:

    [[elasticsearch.type]]
      # Index can be inferred from document ID by including a capturing group named "index".
      # This example matches IDs that start with one or more characters followed by "::".
      # It directs "user::alice" to index "user", and "foo::bar::123" to index "foo".
      regex = '(?<index>.+?)::.*'
