### ISSUE TITLE
Multiple group in same bucket not working properly.

### ISSUE THREAD

**Issue by ozzimpact** [couchbase/couchbase-elasticsearch-connector#199]
Hi, 
I deployed more than one worker group with different group names. Same source but different target. Ex: 
BucketName: Product groupname: product-v1 targetIndex: product-v1
BucketName: Product groupname: product-v2 targetIndex: product-v2

Both of them are 4 membered groups. All get their member numbers according to document 1,2,3,4.
Anyway, in this way I cannot get the document count from elastic even though they are originated from different group names.

I attached example screen shot.

![screen shot 2018-10-25 at 21 54 34](https://user-images.githubusercontent.com/6742827/47523676-41331080-d8a1-11e8-80ab-9335001e4788.png)

**Comment by dnault** [comment]
> All get their member numbers according to document 1,2,3,4.

Can you explain this some more, please? The configuration must be the same for all connectors in a group, except for the `memberNumber`.

It might help if you posted your config files.

**Comment by ozzimpact** [comment]
```
[group]
  name = 'dummy-group-v20181024'

[group.static]
  memberNumber = 1
  totalMembers = 4
[metrics]
  httpPort = 31415
  logInterval = '1m'

[truststore]
  path = 'path/to/truststore'
  pathToPassword = 'secrets/truststore-password.toml'

[couchbase]
  hosts = ["couchbase"]
  bucket = 'DUMMY_BUCKET'
  username = 'Administrator'
  pathToPassword = 'secrets/couchbase-password.toml'
  secureConnection = false

[couchbase.dcp]
  compression = true
  flowControlBuffer = '64mb'
  persistencePollingInterval = '0ms'

[elasticsearch]
  hosts = ["elasticsearch"]
  username = 'elastic'
  pathToPassword = 'secrets/elasticsearch-password.toml'
  secureConnection = false

[elasticsearch.bulkRequestLimits]
  bytes = '10mb'
  actions = 500
  timeout = '1m'
  concurrentRequests = 2

[elasticsearch.docStructure]
  metadataFieldName = 'meta'
  documentContentAtTopLevel = false
  wrapCounters = false

[elasticsearch.typeDefaults]
  index = 'dummy_index_v20181024'
  pipeline = ''
  typeName = 'dummytype'
  ignore = false
  ignoreDeletes = false

[[elasticsearch.type]]
  prefix = '_sync:'
  ignore = true

[[elasticsearch.type]]
  prefix = ''
  index = 'dummy_index_v20181024'
  pipeline = ''

[elasticsearch.rejectionLog]
  index = 'cbes-rejects'
  typeName = '_doc'
```
Second
```
[group]
  name = 'dummy-group-v20181025'

[group.static]
  memberNumber = 1
  totalMembers = 4
[metrics]
  httpPort = 31415
  logInterval = '1m'

[truststore]
  path = 'path/to/truststore'
  pathToPassword = 'secrets/truststore-password.toml'

[couchbase]
  hosts = ["couchbase"]
  bucket = 'DUMMY_BUCKET'
  username = 'Administrator'
  pathToPassword = 'secrets/couchbase-password.toml'
  secureConnection = false

[couchbase.dcp]
  compression = true
  flowControlBuffer = '64mb'
  persistencePollingInterval = '0ms'

[elasticsearch]
  hosts = ["elasticsearch"]
  username = 'elastic'
  pathToPassword = 'secrets/elasticsearch-password.toml'
  secureConnection = false

[elasticsearch.bulkRequestLimits]
  bytes = '10mb'
  actions = 500
  timeout = '1m'
  concurrentRequests = 2

[elasticsearch.docStructure]
  metadataFieldName = 'meta'
  documentContentAtTopLevel = false
  wrapCounters = false

[elasticsearch.typeDefaults]
  index = 'dummy_index_v20181025'
  pipeline = ''
  typeName = 'dummytype'
  ignore = false
  ignoreDeletes = false

[[elasticsearch.type]]
  prefix = '_sync:'
  ignore = true

[[elasticsearch.type]]
  prefix = ''
  index = 'dummy_index_v20181025'
  pipeline = ''

[elasticsearch.rejectionLog]
  index = 'cbes-rejects'
  typeName = '_doc'
```

**Comment by ozzimpact** [comment]
I solved the problem. It is not related with this tool nor its configuration. Its working perfectly fine and performant. Its about my docker image version. But I would appreciate additional performance improvements about configs I posted.

Thanks for your quick reply.

**Comment by dnault** [comment]
For performance tuning, experiment with the values in the [bulk request limits config section](https://docs.couchbase.com/elasticsearch-connector/4.0/configuration.html#bulk-request-limits).

The Elasticsearch documentation also has suggestions for [tuning Elasticsearch for indexing speed](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html).
