### ISSUE TITLE
Ability to use environment variables inside config

### ISSUE THREAD

**Issue by BitPhinix** [couchbase/couchbase-elasticsearch-connector#200]
I would be very useful to be able to use environment variables inside the connector config (like in version 2.1)

Are there any plans to add the feature back into the connector?

**Comment by dnault** [comment]
Sounds like a reasonable feature request. In the mean time, maybe the `envsubst` command can help?

https://stackoverflow.com/a/41936996/611819

**Comment by dnault** [comment]
Issue migrated to Couchbase Jira: https://issues.couchbase.com/browse/CBES-90

Couchbase Jira is open to everyone. If you don't already have an account, sign up by clicking the "contact your Jira administrators" link on the login form.
