### ISSUE TITLE
ElasticSearch 7 support

### ISSUE THREAD

**Issue by zzvara** [couchbase/couchbase-elasticsearch-connector#201]
I have been searching through breaking changes of ES 7 [1], and could not find anything that would considerably interfere with the effort to make the connector work.

I'm planning to experiment on this. Is there anyone done any preliminary work on this?

[1] https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-7.0.html

**Comment by dnault** [comment]
Haven't tested it, but I agree; there's nothing in that list that should prevent the connector from working with ES 7.

**Comment by dnault** [comment]
Issue migrated to Couchbase Jira: https://issues.couchbase.com/browse/CBES-89

Couchbase Jira is open to everyone. If you don't already have an account, you can sign up by clicking the "contact your Jira administrators" link on the login form.
