### ISSUE TITLE
DcpChannel channel close notifications and high cpu utilization

### ISSUE THREAD

**Issue by lexicalparadox** [couchbase/couchbase-elasticsearch-connector#202]
Hi,

We're running the couchbase-elasticsearch-connector-4.0.0 GA release version. We've setup the connector to talk to both CB and ES over SSL (secureConnection=true in the config.toml file) but we're seeing the following in our logs, continuously:

[nioEventLoopGroup-5-15] DEBUG c.c.c.d.c.DcpChannel - Got notified of channel close on Node $nodename/$ip:11207
[nioEventLoopGroup-5-18] INFO  c.c.c.d.c.DcpChannel - Node $nodename/$ip:11207 socket closed, initiating reconnect.

We've setup the keystore properly and have included all the certs/ca into the keystore in order to talk to Couchbase over a secure channel. We're using Couchbase 5.5.2 and ES 6.4.2. Any reason why the connector keeps getting notified from CB to close the connection? As I understand it, 11207 is the SSL port to access the bucket.

We're also seeing super high CPU utilization, consistently, even when we aren't indexing any new documents into CB. We've disabled compression in the CBES config as well. We're thinking that these connection resets are the cause of the CPU utilization. Any ideas?

Thanks,
Lex

**Comment by dnault** [comment]
Is there anything else in the log apart from those two messages?

Does this happen only with `secureConnection=true` in the Couchbase config section?

> As I understand it, 11207 is the SSL port to access the bucket.

Yes, that's correct.

**Comment by dnault** [comment]
Issue migrated to Couchbase Jira: https://issues.couchbase.com/browse/CBES-93

Couchbase Jira is open to everyone. If you don't already have an account, sign up by clicking the "contact your Jira administrators" link on the login form.

**Comment by dnault** [comment]
Hi Lex, let's continue the investigation over on Couchbase Jira.
