### ISSUE TITLE
Support overriding documentTypes settings via ES's dynamic settings API

### ISSUE THREAD

**Issue by synhershko** [couchbase/couchbase-elasticsearch-connector#63]
Currently it is not possible to change the type settings of the XDCR replication without a full cluster restart, and this is highly problematic, especially since both products are schemaless.

I.e. I want to be able to add `couchbase.documentTypes.review: ^review-(\d)+$` to the plugin settings without requiring a restart. Just like mappings can be changed dynamically on an ES cluster, the transport plugin types support needs the ability to define new "types" without requiring any restart.

This shouldn't be too hard to do as Elasticsearch pretty much has built in support for this type of thing.

**Comment by dnault** [comment]
Version 4 of the connector is a standalone process than can be reconfigured and restarted independently of Elasticsearch. This means no ES cluster downtime is required to change the connector settings.
