### ISSUE TITLE
Filter documents by document content

### ISSUE THREAD

**Issue by ramid** [couchbase/couchbase-elasticsearch-connector#66]

**Comment by MalhotraKaran** [comment]
+1

**Comment by dnault** [comment]
@brett19 Seems like a great application for JSONSM.

**Comment by dnault** [comment]
Issue migrated to Couchbase Jira: https://issues.couchbase.com/browse/CBES-92

Couchbase Jira is open to everyone. If you don't already have an account, sign up by clicking the "contact your Jira administrators" link on the login form.
