### ISSUE TITLE
encryption of couchbase.password  in elasticsearch.yml?

### ISSUE THREAD

**Issue by rajeshetty** [couchbase/couchbase-elasticsearch-connector#73]
For couchbase-elasticsearch plugin , we have to have couchbase.password field in elasticsearch.yml file and its in open text and not encrypted. Question is is there any way to encrypt this and make it work?.
  It is more important , if we involve external hosting providers to manage ES cluster , we will have to share this information with them to setup the cluster nodes as per our requirement. It is a security concern. 

Any recommendations ?

-Thanks
Rajesh

**Comment by Branor** [comment]
@rajeshetty I've added this to the next plugin milestone after the current. (Too late for the upcoming release, it's already in QA.)

**Comment by rajeshetty** [comment]
@Branor thanks. that will be really great!.

**Comment by rajeshetty** [comment]
Another quick question, Do you know if couchbase.username have to be the admin user or can read only user work for this?.

**Comment by phrend** [comment]
For now, you may be able to get around this problem by storing the user/pass in environment variables (set via the init script, or any other way you like) and using them in your elasticsearch.yml like:
couchbase.username: $CB_USER
couchbase.password: $CB_PASS

I do something like this, and it does work. (Of course, if the hosting provider can become root, or the user that you use to run elasticsearch, this will not solve your problem.)

**Comment by rajeshetty** [comment]
Any update on this?. Will this be in for upcoming rev of the plugin?

**Comment by dnault** [comment]
@rajeshetty 

> Do you know if couchbase.username have to be the admin user or can read only user work for this?

You can use any username you like. It does not have to correspond to an existing Couchbase user. The only requirement is that you specify the same username/password when setting up the "Remote Cluster" for the ES plugin.

>Any update on this?

Not at the moment. It's unclear what the path forward should be.

**Comment by rajeshetty** [comment]
@dnault it will be very useful to have this feature, as its possible that people may be hosting with some hosting provider and in that case have to share password. even if its a read only user still its a security risk. encryption of password from CB XDCR and ES plugin side would solve this problem.

**Comment by dnault** [comment]
Agreed, this is an issue to be taken seriously.

The security risk can be mitigated by using credentials that do to match any Couchbase user on the source cluster. That way, an attacker cannot use leaked credentials to read or modify the contents of Couchbase. Worst they could do is impersonate the source cluster and try to inject documents into ES (which would still be bad, but it's a different kind of threat).

**Comment by dnault** [comment]
Version 4 of the connector is deployed as a standalone process, configured independently from the ES cluster.  Hopefully this will mitigate some of the concern about credential management. We still don't have a great answer for this, though,
