### ISSUE TITLE
support XDCR Protocol version 2

### ISSUE THREAD

**Issue by android-programmer** [couchbase/couchbase-elasticsearch-connector#76]
My system has TBs data, the version 1.0 XDCR seems to be reluctant to replicate data fast enough.
It takes hours or days to complete to the replication..
It will be awesome if it supports version 2.0 protocal

**Comment by android-programmer** [comment]
+1

**Comment by CriztianiX** [comment]
+1

**Comment by atom992** [comment]
+1

**Comment by veacks** [comment]
+1

**Comment by WillGardella** [comment]
We're still working on support for the Elasticsearch plugin with Couchbase Server 4. It sounds like you encountered a known issue with using the plugin in Couchbase Server 4.0 ([MB-16244](https://issues.couchbase.com/browse/MB-16244)). There are some steps listed there that you can take to reduce the impact of that issue until a fix is issued.

**Comment by mnavarro-ob** [comment]
Is there something that I can do to help creating the support for protocol version 2?

**Comment by igorekpotworek** [comment]
+1

**Comment by igorekpotworek** [comment]
+1

**Comment by lucabelluccini** [comment]
Is this issue still applicable for 2.x versions?

**Comment by dnault** [comment]
@lucabelluccini Yes, the 2.x versions still use XDCR version 1 (also known as CAPI). We're in the earliest stages of developing a new version of the plugin to address this issue.

**Comment by dnault** [comment]
We've just released Couchbase Elasticsearch Connector 4.0.0-dp.1 (Developer Preview) which uses DCP instead of CAPI, supports secure connections, supports Elasticsearch 5 & 6, and offers tools for replication checkpoint management.

  https://github.com/couchbaselabs/couchbase-elasticsearch-connector/releases/tag/4.0.0-dp.1

Please try it out and let us know how it can be improved.

**Comment by dnault** [comment]
Version 4 of the connector has entered GA. It does not use CAPI. It's now reasonable to expect Elasticsearch indexing speed to be the primary performance bottleneck.
