### ISSUE TITLE
Support mapping one bucket to one or more indices

### ISSUE THREAD

**Issue by couchbasebrian** [couchbase/couchbase-elasticsearch-connector#87]
This is a feature request to be able to send documents from one bucket to one or more different indexes, for example, based on document type.

**Comment by chenbekor** [comment]
+1

**Comment by miridfd** [comment]
+1

**Comment by longwatertech** [comment]
+1

**Comment by dnault** [comment]
Version 4 of the connector lets you [define rules](https://docs.couchbase.com/elasticsearch-connector/4.0/configuration.html#type-definitions) to route documents to different indexes based on ID.
